### ISSUE TITLE
ImportError: No module named 'config'

### ISSUE THREAD

**Issue by SeekPoint** [andreamad8/EntNet#2]
mldl@mldlUB1604:~/ub16_prj/QDREN/CNN$ python3 run_final.py 
Traceback (most recent call last):
  File "run_final.py", line 10, in <module>
    from src.utils.ulilz_CNN import Dataset
  File "/home/mldl/ub16_prj/QDREN/CNN/src/utils/ulilz_CNN.py", line 2, in <module>
    import config
ImportError: No module named 'config'
mldl@mldlUB1604:~/ub16_prj/QDREN/CNN$

**Comment by andreamad8** [comment]
You need to install the package config.

`pip install config`

I will add the dependency on the read me.

**Comment by SeekPoint** [comment]
also , just delete all 'import config' looks works well

**Comment by andreamad8** [comment]
Thx.

**Comment by yein920** [comment]
thx:)
