### ISSUE TITLE
TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by SeekPoint** [andreamad8/EntNet#3]
mldl@mldlUB1604:~/ub16_prj/QDREN/bAbI$ PYTHONPATH=src python3 run_final.py 15
/usr/local/lib/python3.5/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/usr/local/lib/python3.5/dist-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
08-07 23:14 Longest sentence length: 6
08-07 23:14 Longest story length: 8
08-07 23:14 Average story length: 8
08-07 23:14 Training sample: 900
08-07 23:14 Validation sample: 100
08-07 23:14 Test sample: 1000
08-07 23:14 Vocab size : 18
08-07 23:14 Embeddings: 18 x 100
08-07 23:14 Loading embedding file: data/glove.6B.100d.txt
08-07 23:14 Pre-trained: 17 (94.44%)
08-07 23:14 Parameters: 49000
08-07 23:14 Initializing Variables!
08-07 23:14 Training stated
08-07 23:14 Epoch 0	Train Loss: 4.137	Train Accuracy: 0.206
08-07 23:14 Start plotting
Traceback (most recent call last):
  File "run_final.py", line 88, in <module>
    main(task_num=sys.argv[1])
  File "run_final.py", line 64, in main
    t = train(epoch,params['bz'], data, par, dr=params['dr'], _test=True)
  File "/home/mldl/ub16_prj/QDREN/bAbI/src/trainer/train.py", line 128, in train
    val_loss[e], val_acc[e] = val_test(all_val,'Validation')
  File "/home/mldl/ub16_prj/QDREN/bAbI/src/trainer/train.py", line 85, in val_test
    viz(e)
  File "/home/mldl/ub16_prj/QDREN/bAbI/src/trainer/train.py", line 59, in viz
    for i in range(l):
TypeError: only integer scalar arrays can be converted to a scalar index
mldl@mldlUB1604:~/ub16_prj/QDREN/bAbI$ 
mldl@mldlUB1604:~/ub16_prj/QDREN/bAbI$

**Comment by andreamad8** [comment]
Thx, this is a bug.

**Comment by SeekPoint** [comment]
I just fixed by add int(l)

**Comment by andreamad8** [comment]
Ok, I added too.
