### ISSUE TITLE
ImportError: No module named 'data.email_util'

### ISSUE THREAD

**Issue by SeekPoint** [andreamad8/EntNet#4]
mldl@mldlUB1604:~/ub16_prj/QDREN/CNN$ 
mldl@mldlUB1604:~/ub16_prj/QDREN/CNN$ PYTHONPATH=src python3 run_final.py 
Traceback (most recent call last):
  File "run_final.py", line 11, in <module>
    from src.trainer.train import train
  File "/home/mldl/ub16_prj/QDREN/CNN/src/trainer/train.py", line 18, in <module>
    from data.email_util import send_email
ImportError: No module named 'data.email_util'
mldl@mldlUB1604:~/ub16_prj/QDREN/CNN$

**Comment by andreamad8** [comment]
yep, another file that I need to fix. 
The 'data.email_util' was not committed because there was info about my email (I was sending info to my email once every 10 epoch). 

I will fix now. 

Thanks for the notice :)
